//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using System.Data.SQLite;
using System;

namespace Model
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<CITA>();
                db.CreateTable<CLIENTE>();
                db.CreateTable<DIETA>();
                db.CreateTable<EJERCICIO>();
                db.CreateTable<RUTINA>();
                db.CreateTable<RUTINA_SESION>();
                db.CreateTable<SESION_EJERCICIO>();
                db.CreateTable<USUARIO>();
            }
        }
    }
    public partial class CITA
    {
        [PrimaryKey]
        public Int64 ID { get; set; }
        
        [NotNull]
        public String ENTRENADOR { get; set; }
        
        [NotNull]
        public Int64 CLIENTE { get; set; }
        
        [NotNull]
        public String FECHA { get; set; }
        
        [NotNull]
        public String HORA { get; set; }
        
    }
    
    public partial class CLIENTE
    {
        [PrimaryKey]
        public Int64 ID { get; set; }
        
        [NotNull]
        public String NOMBRE { get; set; }
        
    }
    
    public partial class DIETA
    {
        [PrimaryKey]
        public Int64 ID { get; set; }
        
        [NotNull]
        public Int64 ID_RUTINA { get; set; }
        
        [NotNull]
        public String LUNES { get; set; }
        
        [NotNull]
        public String MARTES { get; set; }
        
        [NotNull]
        public String MIERCOLES { get; set; }
        
        [NotNull]
        public String JUEVES { get; set; }
        
        [NotNull]
        public String VIERNES { get; set; }
        
        [NotNull]
        public String SABADO { get; set; }
        
        [NotNull]
        public String DOMINGO { get; set; }
        
    }
    
    public partial class EJERCICIO
    {
        [PrimaryKey]
        public String NOMBRE { get; set; }
        
        [NotNull]
        public String TIPO { get; set; }
        
        [NotNull]
        public Int64 DURACION { get; set; }
        
        [NotNull]
        public String DESCRIPICION { get; set; }
        
        [NotNull]
        public String PRIVACIDAD { get; set; }
        
        [NotNull]
        public String VIDEO { get; set; }
        
    }
    
    public partial class RUTINA
    {
        [PrimaryKey]
        public Int64 ID { get; set; }
        
        [NotNull]
        public Int64 ID_CLIENTE { get; set; }
        
    }
    
    public partial class RUTINA_SESION
    {
        [PrimaryKey]
        public Int64 Id { get; set; }
        
        [NotNull]
        public Int64 ID_RUTINA { get; set; }
        
        [NotNull]
        public Int64 ID_SESION { get; set; }
        
    }
    
    public partial class SESION_EJERCICIO
    {
        [PrimaryKey]
        public Int64 ID { get; set; }
        
        [NotNull]
        public Int64 SESION { get; set; }
        
        [NotNull]
        public String EJERCICIO { get; set; }
        
    }
    
    public partial class USUARIO
    {
        [PrimaryKey]
        public String USERNAME { get; set; }
        
        [NotNull]
        public String PASSWORD { get; set; }
        
    }
    
}
